### ISSUE TITLE
替代手写这功能好实用，太棒了。顺带一点建议

### ISSUE THREAD

**Issue by yongliyongli** [why20021008/hand-write#1]
这程序解决了一大痛点哇，up好棒！然后看了源代码，有2点建议：

1 pyqt就有获取文件路径的函数，可以替代TK，这样打包出来的文件应该可以更小。例： QFileDialog.getOpenFileName(self, "请选择文件夹路径", "./")
2 可以把qt design生成的gui和自己写的主函数分离成两个文件，自己的主函数用类继承的方法直接调用gui的变量，这样gui界面随时可以用qt design增减按钮，同时又不影响自己的主函数。例：class MyRun(QMainWindow, Ui_Form)：
def __init__(self,parent=None):
    super(MyRun, self).__init__(parent)
    self.setupUi(self)
    下面正常写自己的程序部分就好了

**Comment by why20021008** [comment]
大佬，我python还不太会，因为我们工程计算课程设计要用，所以就去学了python和pyqt。
多线程什么的我都没看，等我看到一定会改进的。谢谢大佬的建议。
我代码基本都是百度的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "why20021008/hand-write"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月4日(星期一) 晚上10:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[why20021008/hand-write] 替代手写这功能好实用，太棒了。顺带一点建议 (Issue #1)





 
这程序解决了一大痛点哇，up好棒！然后看了源代码，有2点建议：
 
1 pyqt就有获取文件路径的函数，可以替代TK，这样打包出来的文件应该可以更小。例： QFileDialog.getOpenFileName(self, "请选择文件夹路径", "./")
 2 可以把qt design生成的gui和自己写的主函数分离成两个文件，自己的主函数用类继承的方法直接调用gui的变量，这样gui界面随时可以用qt design增减按钮，同时又不影响自己的主函数。例：class MyRun(QMainWindow, Ui_Form)：
 def init(self,parent=None):
 super(MyRun, self).init(parent)
 self.setupUi(self)
 下面正常写自己的程序部分就好了

**Comment by yongliyongli** [comment]
加油哈 期待3.0

**Comment by takiya562** [comment]
到底要用什么字体啊，显示的都是一个一个的方框
